spring:
  application:
    name: dailyfeed-batch-svc

  profiles:
    active: local

  # Spring Batch 설정
  batch:
    job:
      enabled: false  # 애플리케이션 시작 시 자동 실행 방지
    jdbc:
      initialize-schema: always  # 배치 메타데이터 테이블 자동 생성

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100

  # 데이터소스 설정
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:batchdb
    username: sa
    password:

  # H2 콘솔 활성화
  h2:
    console:
      enabled: true
      path: /h2-console

# 로깅 설정
logging:
  level:
    root: INFO
    click.dailyfeed.batch: DEBUG
    org.springframework.batch: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
